services:
  mvp-portfolio-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mvp-portfolio-service-dev
    ports:
      - "8101:8080"
    env_file:
      - .env
    networks:
    - mvp-nw-dev 
    command: ["mvn", "spring-boot:run"]
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "5"
    volumes:
      - .:/app

networks:
  mvp-nw-dev:
    external: true

