name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write


jobs:
  deploy:
    uses: mv-port/actions/.github/workflows/deploy.yml@deploy-2.0
    secrets: inherit
